#!/usr/bin/env bash
# Folder : /home/bin/
# florent@linguenheld.fr 2025

ALACRITTY_FILE="$HOME/.config/alacritty/alacritty.toml"
ALACRITTY_REG="themes/.*\.toml"

WEZTERM_FILE="$HOME/.wezterm.lua"
WEZTERM_REG="config\.color_scheme = '.*'"

HELIX_FILE="$HOME/.config/helix/config.toml"
HELIX_REG="theme = \".*\""

STARSHIP_FILE="$HOME/.config/starship.toml"
STARSHIP_REG="palette = \".*\""

ZELLIJ_FILE="$HOME/.config/zellij/config.kdl"
ZELLIJ_REG="^theme \".*\""

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------- THEMES ---

THEMES=(   'catppuccin_frappe' 'catppuccin_latte'  'catppuccin_macchiato' 'catppuccin_mocha' 'gruvbox'             'gruvbox_light'  'onedark'         'onelight')
THEMES_ST=('catppuccin_frappe' 'catppuccin_latte'  'catppuccin_macchiato' 'catppuccin_mocha' 'gruvbox'             'gruvbox_light'  'oneyellow'       'onelight')
THEMES_WZ=('Catppuccin Frappe' 'Catppuccin Latte'  'Catppuccin Macchiato' 'Catppuccin Mocha' 'Gruvbox Dark (Gogh)' 'Gruvbox (Gogh)' 'One Dark (Gogh)' 'One Light (Gogh)')

# ------------------------------------------------------------------------------
# Get the index of the given theme in $THEMES
# (0 if not found)
get_index() {
  
  for index in "${!THEMES[@]}"; do
    if [[ "${THEMES[$index]}" == "$1" ]]; then
      echo "$index"
      exit
    fi
  done
  echo "0"
}

# ------------------------------------------------------------------------------
usage() {
  echo "Usage: $(basename "${0}") [OPTION]"
  echo "  Get the current helix theme"
  echo "  Then get the next theme in the saved list"
  echo "  And update the Helix, Wezterm, Alacritty and Starship config files with the next theme."
  echo "  Set the gnome color scheme to light or dark according to the new theme"
  echo
  echo "     -h HELP:        display this message."
}

MODE="next"
while getopts hm OPTION; do

  case ${OPTION} in
    h)
      usage
      exit 0
    ;;
    ?)
      usage
      exit 1
    ;;
  esac
done

# ---------------------------------------------------------------------------------------
CURRENT=$(grep "$HELIX_REG" "$HELIX_FILE" | awk -F '"' '{print $2}')

INDEX=$(get_index "$CURRENT")
((INDEX++))
if [[ "$INDEX" -eq "${#THEMES[@]}" ]]; then
  INDEX="0"
fi

echo "new one  ${THEMES[$INDEX]}"

sed -i "s#${HELIX_REG}#theme = \"${THEMES[$INDEX]}\"#" "${HELIX_FILE}"
sed -i "s#${ALACRITTY_REG}#themes/${THEMES[$INDEX]}.toml#" "${ALACRITTY_FILE}"
sed -i "s#${WEZTERM_REG}#config.color_scheme = '${THEMES_WZ[$INDEX]}'#" "${WEZTERM_FILE}"
sed -i "s#${STARSHIP_REG}#palette = \"${THEMES_ST[$INDEX]}\"#" "${STARSHIP_FILE}"
sed -i "s#${ZELLIJ_REG}#theme \"${THEMES[$INDEX]}\"#" "${ZELLIJ_FILE}"

# Due to the appimage, the signal has to be sent to the PID of each running helix
pgrep -f usr/bin/hx | while read -r PID; do
  kill -USR1 "$PID" 2> /dev/null
done

# Up gnome style
if [[ "${THEMES[$INDEX]}" =~ "light" || "${THEMES[$INDEX]}" =~ "latte" ]]; then
  gsettings set org.gnome.desktop.interface color-scheme "'prefer-light'"
else
  gsettings set org.gnome.desktop.interface color-scheme "'prefer-dark'"
fi

notify-send "✨ New theme: ${THEMES_WZ[$INDEX]} ✨ "
echo "New theme: ${THEMES_WZ[$INDEX]}"
exit 0
